import Ionicons from '@expo/vector-icons/Ionicons';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { Image } from 'expo-image';
import { useState } from 'react';
import { FlatList, Pressable, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { BrandIcon } from '@/components/home/brand-icon';
import { FeedSheet } from '@/components/home/feed-sheet';
import { TabScreen } from '@/components/home/tab-screen';
import { explorePosts, suggestedPeople, topics, trendingCreators, type ExplorePerson, type ExplorePost } from '@/data/demo-explore';

type Mode = 'All' | 'People' | 'Posts' | 'Tags';
type Sheet = { kind: 'person' | 'options'; person: ExplorePerson } | { kind: 'post'; post: ExplorePost } | { kind: 'suggested' | 'trending' | 'notifications' } | null;
export function ExploreScreen() {
  const { width } = useWindowDimensions();
  const insets = useSafeAreaInsets();
  const contentWidth = Math.min(width, 520);
  const cellWidth = (contentWidth - 16) / 3;
  const personWidth = Math.max(60, (contentWidth - 78) / 5);
  const creatorWidth = Math.max(112, (contentWidth - 40) / 3);
  const [query, setQuery] = useState('');
  const [mode, setMode] = useState<Mode>('All');
  const [topic, setTopic] = useState<string>('For You');
  const [following, setFollowing] = useState<string[]>([]);
  const [saved, setSaved] = useState<string[]>([]);
  const [hidden, setHidden] = useState<string[]>([]);
  const [sheet, setSheet] = useState<Sheet>(null);
  const [unread, setUnread] = useState(3);
  const [notice, setNotice] = useState('');
  const search = query.trim().toLowerCase().replace(/^#/, '');
  const matchesPerson = (person: ExplorePerson) => `${person.name} ${person.category}`.toLowerCase().includes(search) && !hidden.includes(person.name);
  const people = suggestedPeople.filter(matchesPerson);
  const creators = trendingCreators.filter(matchesPerson);
  const posts = explorePosts.filter(post => (topic === 'For You' || post.topics.includes(topic)) && `${post.title} ${post.location} ${post.topics.join(' ')}`.toLowerCase().includes(search));
  const tags = topics.slice(1).filter(tag => tag.toLowerCase().includes(search));
  const toggleFollow = (name: string) => setFollowing(current => current.includes(name) ? current.filter(item => item !== name) : [...current, name]);
  function open(next: Sheet) { setNotice(''); setSheet(next); }
  function followButton(person: ExplorePerson, light = false) {
    const followed = following.includes(person.name);
    return <Pressable accessibilityRole="button" accessibilityLabel={`${followed ? 'Unfollow' : 'Follow'} ${person.name}`} accessibilityState={{ selected: followed }} aria-pressed={followed} onPress={() => toggleFollow(person.name)} style={[styles.follow, light && styles.followLight, followed && !light && { backgroundColor: '#eaf3ff' }]}><Text style={[styles.followText, (light || followed) && { color: '#0876ff' }]}>{followed ? 'Following' : 'Follow'}</Text></Pressable>;
  }
  function personRow(person: ExplorePerson) { return <View key={person.name} style={styles.personRow}><Pressable accessibilityRole="button" accessibilityLabel={`View ${person.name}`} onPress={() => open({ kind: 'person', person })} style={styles.rowIdentity}><Image source={person.avatar} style={styles.rowAvatar} contentFit="cover" /><View style={{ flex: 1 }}><Text style={styles.body}>{person.name}</Text><Text style={styles.helper}>{person.category}</Text></View></Pressable><View style={{ width: 80 }}>{followButton(person)}</View></View>; }
  const showPeople = mode === 'All' || mode === 'People';
  const showPosts = mode === 'All' || mode === 'Posts';
  return <TabScreen><View style={[styles.screen, { paddingTop: insets.top }]}><View style={{ flex: 1, width: contentWidth, alignSelf: 'center' }}>
    <View style={styles.header}><BrandIcon size={42} /><Text style={styles.brand}>Codexgram</Text><Pressable accessibilityRole="button" accessibilityLabel="Explore notifications" onPress={() => open({ kind: 'notifications' })} style={styles.bell}><Ionicons name="notifications-outline" size={25} color="#11172b" />{unread > 0 && <View style={styles.badge}><Text style={styles.badgeText}>{unread}</Text></View>}</Pressable></View>
    <View style={styles.search}><Ionicons name="search-outline" size={21} color="#626c89" /><TextInput accessibilityLabel="Search people, places, or posts" placeholder="Search people, places, or posts..." placeholderTextColor="#838da9" value={query} onChangeText={setQuery} autoCapitalize="none" returnKeyType="search" style={styles.searchInput} />{!!query && <Pressable accessibilityRole="button" accessibilityLabel="Clear search" onPress={() => setQuery('')} style={{ padding: 4 }}><Ionicons name="close-circle" size={20} color="#838da9" /></Pressable>}</View>
    <View accessibilityRole="tablist" style={styles.modes}>{(['All', 'People', 'Posts', 'Tags'] as const).map(item => <Pressable key={item} accessibilityRole="tab" accessibilityLabel={`${item} results`} accessibilityState={{ selected: mode === item }} aria-selected={mode === item} onPress={() => setMode(item)} style={[styles.mode, mode === item && styles.active]}><Text style={[styles.modeText, mode === item && styles.white]}>{item}</Text></Pressable>)}</View>
    <FlatList data={showPosts ? posts : []} numColumns={3} keyExtractor={item => item.id} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled" contentContainerStyle={{ paddingBottom: 8 }} columnWrapperStyle={styles.gridRow}
      ListHeaderComponent={<>
        {showPeople && <>
          <View style={styles.sectionTitle}><Text style={styles.heading}>Suggested for you</Text><Pressable accessibilityRole="button" accessibilityLabel="See all suggested people" onPress={() => open({ kind: 'suggested' })} hitSlop={8}><Text style={styles.seeAll}>See All</Text></Pressable></View>
          <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.suggestions} keyboardShouldPersistTaps="handled">{people.map(person => <View key={person.name} style={{ width: personWidth, alignItems: 'stretch' }}><Pressable accessibilityRole="button" accessibilityLabel={`View ${person.name}`} onPress={() => open({ kind: 'person', person })} style={{ alignItems: 'center' }}><View style={styles.avatarClip}><Image source={person.avatar} contentFit="cover" style={person.name === 'sarah.chen' || person.name === 'olivia.martin' ? { width: 87, height: 87, left: -19, top: -7 } : styles.avatar} /></View><View style={styles.personName}><Text numberOfLines={1} style={styles.username}>{person.name}</Text><MaterialIcons name="verified" size={9} color="#0876ff" /></View><Text numberOfLines={1} style={styles.category}>{person.category}</Text></Pressable>{followButton(person)}</View>)}</ScrollView>
          {!people.length && <Text style={styles.noResults}>No matching people.</Text>}
          <View style={[styles.sectionTitle, { marginTop: 13 }]}><Text style={styles.heading}>Trending Creators</Text><Pressable accessibilityRole="button" accessibilityLabel="See all trending creators" onPress={() => open({ kind: 'trending' })} hitSlop={8}><Text style={styles.seeAll}>See All</Text></Pressable></View>
          <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.creators} keyboardShouldPersistTaps="handled">{creators.map(person => <View key={person.name} style={[styles.creator, { width: creatorWidth }]}>
            <Pressable accessibilityRole="button" accessibilityLabel={`View ${person.name}`} onPress={() => open({ kind: 'person', person })} style={StyleSheet.absoluteFill}><Image source={person.cover} contentFit="cover" style={StyleSheet.absoluteFill} /></Pressable>
            <View style={styles.creatorInfo}><Pressable accessibilityRole="button" accessibilityLabel={`View creator ${person.name}`} onPress={() => open({ kind: 'person', person })} style={styles.creatorIdentity}><Image source={person.avatar} style={styles.creatorAvatar} /><View style={{ flex: 1 }}><View style={styles.personName}><Text numberOfLines={1} style={styles.creatorName}>{person.name}</Text><MaterialIcons name="verified" size={9} color="#0876ff" /></View><Text style={styles.followerCount}>{person.followers} followers</Text></View></Pressable><View style={{ flexDirection: 'row', alignItems: 'center', gap: 3 }}><View style={{ flex: 1 }}>{followButton(person, true)}</View><Pressable accessibilityRole="button" accessibilityLabel={`Options for ${person.name}`} onPress={() => open({ kind: 'options', person })} style={styles.more}><Ionicons name="ellipsis-horizontal" size={16} color="#fff" /></Pressable></View></View>
          </View>)}</ScrollView>
          {!creators.length && <Text style={styles.noResults}>No matching creators.</Text>}
        </>}
        {mode === 'Tags' && <View style={{ padding: 16 }}>{tags.map(tag => <Pressable key={tag} accessibilityRole="button" accessibilityLabel={`Explore tag ${tag}`} onPress={() => { setMode('Posts'); setTopic(tag); setQuery(''); }} style={styles.tagRow}><Ionicons name="pricetag-outline" size={23} color="#1677ff" /><View><Text style={styles.body}>#{tag.toLowerCase()}</Text><Text style={styles.helper}>{explorePosts.filter(post => post.topics.includes(tag)).length} preview moments</Text></View><Ionicons name="chevron-forward" size={18} color="#838da9" /></Pressable>)}{!tags.length && <Text style={styles.noResults}>No matching tags.</Text>}</View>}
        {showPosts && <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.topics}>{topics.map(item => <Pressable key={item} accessibilityRole="button" accessibilityLabel={`Topic ${item}`} accessibilityState={{ selected: topic === item }} aria-pressed={topic === item} onPress={() => setTopic(item)} style={[styles.topic, item === topic && styles.active]}><Text style={[styles.topicText, item === topic && styles.white]}>{item}</Text></Pressable>)}</ScrollView>}
      </>}
      renderItem={({ item }) => <Pressable accessibilityRole="button" accessibilityLabel={`Open ${item.title}`} onPress={() => open({ kind: 'post', post: item })} style={{ width: cellWidth, height: cellWidth * 0.82, borderRadius: 8, overflow: 'hidden' }}><Image source={item.source} contentFit="cover" style={StyleSheet.absoluteFill} /><Ionicons name="copy" size={16} color="#fff" style={styles.album} /></Pressable>}
      ListEmptyComponent={showPosts ? <View style={styles.empty}><Ionicons name="search-outline" size={30} color="#838da9" /><Text style={styles.body}>No moments found</Text><Text style={styles.helper}>Try another search or topic.</Text><Pressable accessibilityRole="button" onPress={() => { setQuery(''); setTopic('For You'); }} style={styles.reset}><Text style={styles.white}>Reset search</Text></Pressable></View> : null}
    />
    <FeedSheet visible={sheet !== null} title={sheet?.kind === 'person' ? sheet.person.name : sheet?.kind === 'post' ? sheet.post.title : sheet?.kind === 'options' ? 'Creator options' : sheet?.kind === 'notifications' ? 'Notifications' : sheet?.kind === 'trending' ? 'Trending Creators' : 'Suggested for you'} onClose={() => setSheet(null)}>
      {sheet?.kind === 'person' && <View style={styles.personDetail}><Image source={sheet.person.avatar} style={{ width: 88, height: 88, borderRadius: 44 }} /><Text style={styles.heading}>{sheet.person.name}</Text><Text style={styles.body}>{sheet.person.category}</Text><View style={{ width: 160 }}>{followButton(sheet.person)}</View><Text style={styles.helper}>Preview creator. Follows stay in this session.</Text></View>}
      {sheet?.kind === 'post' && <><Image source={sheet.post.source} contentFit="cover" style={{ width: '100%', aspectRatio: 1, borderRadius: 14 }} /><Text style={[styles.body, { marginTop: 14 }]}>{sheet.post.location}</Text><Text style={styles.helper}>{sheet.post.topics.map(tag => `#${tag.toLowerCase()}`).join(' ')}</Text><Pressable accessibilityRole="button" accessibilityLabel={saved.includes(sheet.post.id) ? 'Unsave moment' : 'Save moment'} onPress={() => { const id = sheet.post.id; setSaved(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]); }} style={styles.tagRow}><Ionicons name={saved.includes(sheet.post.id) ? 'bookmark' : 'bookmark-outline'} size={23} color="#1677ff" /><Text style={styles.body}>{saved.includes(sheet.post.id) ? 'Saved for this session' : 'Save moment'}</Text></Pressable></>}
      {(sheet?.kind === 'suggested' || sheet?.kind === 'trending') && <><Text style={styles.helper}>Discover preview creators. Follows stay in this session.</Text>{(sheet.kind === 'suggested' ? [...suggestedPeople, ...trendingCreators] : [...trendingCreators, ...suggestedPeople]).filter(matchesPerson).map(personRow)}</>}
      {sheet?.kind === 'options' && <><Pressable accessibilityRole="button" accessibilityLabel="Hide this creator" onPress={() => { setHidden(current => [...current, sheet.person.name]); setSheet(null); }} style={styles.tagRow}><Ionicons name="eye-off-outline" size={23} /><Text style={styles.body}>Hide this creator</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Report creator" onPress={() => setNotice('Reporting is not connected in this preview. No report has been sent.')} style={styles.tagRow}><Ionicons name="flag-outline" size={23} /><Text style={styles.body}>Report creator</Text></Pressable></>}
      {sheet?.kind === 'notifications' && <><Text style={styles.helper}>Sample activity in your preview community.</Text>{['sarah.chen shared a new moment.', 'alexwong is trending today.', 'Discover new creators picked for you.'].map(text => <Text key={text} style={[styles.body, { paddingVertical: 12 }]}>{text}</Text>)}<Pressable accessibilityRole="button" onPress={() => { setUnread(0); setNotice('All notifications marked as read.'); }} style={styles.reset}><Text style={styles.white}>Mark all as read</Text></Pressable></>}
      {!!notice && <Text accessibilityRole="alert" style={styles.helper}>{notice}</Text>}
    </FeedSheet>
  </View></View></TabScreen>;
}
const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#fcfdff' }, header: { height: 56, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 17, gap: 10 },
  brand: { fontFamily: 'Inter_700Bold', fontSize: 24, letterSpacing: -1.1, color: '#080b16', flex: 1 }, bell: { width: 40, height: 44, alignItems: 'center', justifyContent: 'center' },
  badge: { position: 'absolute', top: 4, right: 2, width: 16, height: 16, borderRadius: 8, backgroundColor: '#ff102a', alignItems: 'center', justifyContent: 'center' }, badgeText: { color: '#fff', fontFamily: 'Inter_600SemiBold', fontSize: 10 },
  search: { height: 36, marginHorizontal: 14, backgroundColor: '#eef1f8', borderRadius: 9, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, gap: 9 }, searchInput: { flex: 1, minWidth: 0, fontSize: 13.5, fontFamily: 'Inter_400Regular', color: '#161d35', paddingVertical: 0 },
  modes: { flexDirection: 'row', gap: 5, marginHorizontal: 14, marginTop: 8, marginBottom: 0 }, mode: { flex: 1, height: 30, borderRadius: 7, backgroundColor: '#f0f3f9', alignItems: 'center', justifyContent: 'center' }, modeText: { fontFamily: 'Inter_400Regular', fontSize: 10.5, color: '#626e91' }, active: { backgroundColor: '#0876ff' }, white: { color: '#fff' },
  sectionTitle: { height: 25, marginTop: 10, marginHorizontal: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, heading: { fontFamily: 'Inter_700Bold', fontSize: 13, letterSpacing: -0.4, color: '#0b0f1c' }, seeAll: { fontFamily: 'Inter_400Regular', fontSize: 10, color: '#0876ff' },
  suggestions: { paddingHorizontal: 15, gap: 12, minHeight: 110 }, avatarClip: { width: 58, height: 58, borderRadius: 29, overflow: 'hidden' }, avatar: { width: 58, height: 58, borderRadius: 29 }, personName: { flexDirection: 'row', alignItems: 'center', gap: 2, marginTop: 3 }, username: { fontFamily: 'Inter_700Bold', fontSize: 8.5, color: '#101624', letterSpacing: -0.25, flexShrink: 1 }, category: { fontFamily: 'Inter_400Regular', fontSize: 7.5, letterSpacing: -0.15, color: '#8790ad', lineHeight: 13, marginBottom: 3 },
  follow: { height: 21, borderRadius: 5, backgroundColor: '#0876ff', alignItems: 'center', justifyContent: 'center' }, followText: { fontFamily: 'Inter_600SemiBold', fontSize: 9, color: '#fff' }, followLight: { backgroundColor: '#fff', height: 19, borderWidth: 1, borderColor: '#e4e8ee' },
  creators: { paddingHorizontal: 15, gap: 5 }, creator: { height: 120, borderRadius: 7, overflow: 'hidden', backgroundColor: '#d8e4ee' }, creatorInfo: { position: 'absolute', left: 0, right: 0, bottom: 0, padding: 6, backgroundColor: 'rgba(6,25,40,0.65)' }, creatorIdentity: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 5 }, creatorAvatar: { width: 27, height: 27, borderRadius: 14, borderWidth: 2, borderColor: '#fff' }, creatorName: { color: '#fff', fontFamily: 'Inter_600SemiBold', fontSize: 8, flexShrink: 1, letterSpacing: -0.15 }, followerCount: { fontFamily: 'Inter_400Regular', fontSize: 8, color: '#e4eaf1', lineHeight: 12 }, more: { width: 20, minHeight: 23, alignItems: 'center', justifyContent: 'center' },
  topics: { paddingHorizontal: 13, gap: 5, paddingTop: 14, paddingBottom: 8 }, topic: { backgroundColor: '#f0f3f9', height: 24, paddingHorizontal: 8, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, topicText: { fontFamily: 'Inter_400Regular', fontSize: 8.5, color: '#667291' },
  gridRow: { paddingHorizontal: 5, gap: 3, marginBottom: 3 }, album: { position: 'absolute', top: 7, right: 7 },
  noResults: { fontFamily: 'Inter_400Regular', fontSize: 13, color: '#838da9', padding: 16 }, empty: { alignItems: 'center', padding: 25, gap: 10 }, reset: { backgroundColor: '#0876ff', padding: 13, borderRadius: 10, alignItems: 'center' },
  body: { fontFamily: 'Inter_600SemiBold', fontSize: 14, color: '#172039' }, helper: { fontFamily: 'Inter_400Regular', fontSize: 12, lineHeight: 19, color: '#838da9', marginVertical: 6 }, personRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 10 }, rowIdentity: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10 }, rowAvatar: { width: 42, height: 42, borderRadius: 21 }, tagRow: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 58, borderBottomWidth: 1, borderColor: '#eef1f6' }, personDetail: { alignItems: 'center', gap: 12, paddingBottom: 20 },
});
