const {chromium,expect}=require('@playwright/test');const fs=require('node:fs');
(async()=>{const b=await chromium.launch({channel:'msedge'});const p=await b.newPage({viewport:{width:393,height:807}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8082/preview/messages',{waitUntil:'networkidle'});const button=name=>p.getByRole('button',{name,exact:true});const close=async()=>{await button('Close').click();await p.waitForTimeout(350);};await button('Open chat with sarah.chen').click();await expect(p).toHaveURL(/chat-preview$/);await expect(button('Send message')).toBeDisabled();
await button('Open shared photo 1').click();await expect(p.getByRole('heading',{name:'Shared photo'})).toBeVisible();await close();
await button('Play voice message').click();await expect(p.getByText(/no audio file/)).toBeVisible();await close();
await button('Voice call').click();await expect(p.getByText(/No call has been placed/)).toBeVisible();await close();
await button('Video call').click();await expect(p.getByText(/No call has been placed/)).toBeVisible();await close();
await button('View Belvedere Viewpoint location').click();await expect(p.getByText(/Illustrative preview map/)).toBeVisible();await close();
await button('Choose emoji').click();await button('Add 👍').click();await expect(p.getByRole('textbox',{name:'Write a message'})).toHaveValue('👍');
await p.getByRole('textbox',{name:'Write a message'}).fill('Let’s meet by the lake!');await button('Send message').click();await expect(p.getByText('Let’s meet by the lake!',{exact:true}).last()).toBeInViewport();await expect(p.getByRole('textbox',{name:'Write a message'})).toHaveValue('');
await button('Add attachment').click();await button('Attach photo 2').click();await expect(p.getByText('Photo ready to send')).toBeVisible();await button('Remove attachment').click();await expect(p.getByText('Photo ready to send')).toHaveCount(0);
await button('Add attachment').click();await button('Attach photo 1').click();await button('Send message').click();await expect(button('Open your shared photo')).toBeVisible();
await button('Back to messages').click();await expect(p.getByText('You shared a photo',{exact:true})).toBeVisible();await button('Open chat with sarah.chen').click();await expect(p.getByText('Let’s meet by the lake!',{exact:true})).toHaveCount(1);
for(const [width,height]of [[320,568],[414,896]]){await p.setViewportSize({width,height});await p.getByRole('textbox',{name:'Write a message'}).fill('A multiline\nmessage');await expect(button('Send message')).toBeInViewport();if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Overflow');await p.screenshot({path:`design/qa/chat/size-${width}x${height}.png`});}
await p.goto('http://localhost:8082/chat',{waitUntil:'networkidle'});await expect(p).toHaveURL('http://localhost:8082/');if(errors.length)throw Error(errors.join('\n'));const result={passed:true,checks:['messages navigation','empty send disabled','photo preview','audio availability','call availability','location preview','emoji insertion','local text send/autoscroll','attachment add/remove/send','session navigation persistence','responsive composer','signed-out protection'],errors};fs.writeFileSync('design/qa/chat/interaction-results.json',JSON.stringify(result,null,2));console.log(result);await b.close();})().catch(e=>{console.error(e);process.exit(1)});
